In [1]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [2]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

torch.__version__

'1.12.1+cu113'

# Introduction to Tensors

In [3]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [4]:
scaler.ndim

0

In [5]:
scaler.item()

7

In [6]:
vector = torch.tensor([7,7])
vector  

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
matrix = torch.tensor([[7,8],
                       [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
matrix.ndim

2

In [11]:
matrix.shape  

torch.Size([2, 2])

In [12]:
matrix[0]

tensor([7, 8])

In [13]:
tensor = torch.tensor([
    [[1,2,3],[1,2,3],[1,2,3]],
    [[5,6,7],[5,6,7],[5,6,7]],
    [[1,2,3],[1,2,3],[1,2,3]]
    ])
tensor

tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[5, 6, 7],
         [5, 6, 7],
         [5, 6, 7]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]])

In [14]:
tensor.ndim

3

In [15]:
tensor.ndim

3

In [16]:
tensor[1]

tensor([[5, 6, 7],
        [5, 6, 7],
        [5, 6, 7]])

# Creating Tensors

In [17]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8248, 0.1267, 0.6032, 0.9812],
        [0.6001, 0.5619, 0.1368, 0.6813],
        [0.1718, 0.8854, 0.6936, 0.3884]])

In [18]:
random_image_size_tensor = torch.rand(size = (224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [19]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

In [23]:
random_tensor.dtype

torch.float32

In [24]:
torch.range(0,10)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  """Entry point for launching an IPython kernel.


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [25]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
torch.arange(start = 1, end = 1000, step = 77)

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [27]:
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Datatypes

In [28]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None,
                               device = None, # "cuda"
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

# Tensor Attributes

In [31]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [32]:
int_32_tensor = torch.tensor([3,6,9],dtype = torch.long)
int_32_tensor

tensor([3, 6, 9])

In [33]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [34]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.1577, 0.6143, 0.2478, 0.5603],
        [0.8492, 0.0452, 0.4443, 0.7451],
        [0.5665, 0.7504, 0.9862, 0.7938]])

In [35]:
some_tensor.size, some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [36]:
some_tensor.size()

torch.Size([3, 4])

In [37]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.1577, 0.6143, 0.2478, 0.5603],
        [0.8492, 0.0452, 0.4443, 0.7451],
        [0.5665, 0.7504, 0.9862, 0.7938]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


# Manupilating of Tensors

In [38]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [39]:
tensor * 10

tensor([10, 20, 30])

In [40]:
tensor - 10

tensor([-9, -8, -7])

In [41]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [42]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [43]:
tensor

tensor([1, 2, 3])

In [44]:
tensor * tensor

tensor([1, 4, 9])

In [45]:
torch.matmul(tensor,tensor)

tensor(14)

In [48]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 2.06 ms, sys: 4 µs, total: 2.06 ms
Wall time: 2.07 ms


tensor(14)

In [50]:
%%time 
torch.matmul(tensor,tensor)

CPU times: user 505 µs, sys: 0 ns, total: 505 µs
Wall time: 449 µs


tensor(14)

In [53]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.mm(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

# Finding the min, max, mean and sum

In [60]:
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [58]:
torch.min(x),    x.min()

(tensor(0), tensor(0))

In [59]:
torch.max(x),    x.max()

(tensor(90), tensor(90))

In [63]:
torch.mean(x.type(torch.float32)),   x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [66]:
torch.sum(x)   ,  x.sum()

(tensor(450), tensor(450))

In [68]:
torch.argmax(x),    x.argmax()

(tensor(9), tensor(9))

In [69]:
torch.argmin(x),   x.argmin()

(tensor(0), tensor(0))

# Reshaping, viewing, stacking tensors

In [70]:
x  = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [72]:
x_reshaped = x.reshape((3,3))
x_reshaped,  x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]), torch.Size([3, 3]))

In [75]:
z = x.view(1,9)
z,  z.shape
# changing z changes x cuz a view of a tensor shares the same memory

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [78]:
z[:,0] = 5
z, x 
# these are equal

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [88]:
x_stacked = torch.stack([x,x,x,x],dim = 0)
x_stacked, x_stacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([4, 9]))

# Squeezing, unsqueezing and permuting

In [97]:
x = torch.zeros(2,1,2,1,2)
print(x.size())
y = torch.squeeze(x)  # it removes all 1 dimensional tensors
print(y.size())
y = torch.squeeze(x,0)
print(y.size())
y = torch.squeeze(x,1)
print(y.size())

torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 2])
torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 1, 2])


In [104]:
x = torch.randn(2,3,5)
print(x.size())
torch.permute(x,(2,0,1)).size()
# second dim is first, zeros dim is in middle...

torch.Size([2, 3, 5])


torch.Size([5, 2, 3])

In [107]:
x_original = torch.rand(size = (224,224,3))
x_permuted = x_original.permute(2,0,1)
x_permuted.shape

torch.Size([3, 224, 224])

# Indexing

In [109]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [110]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [111]:
x[0][0]

tensor([1, 2, 3])

In [113]:
x[0][2][2]

tensor(9)

In [122]:
x[0,0:2,:]

tensor([[1, 2, 3],
        [4, 5, 6]])

# Reproducibility

In [124]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.4610, 0.9547, 0.6131, 0.2805],
        [0.2667, 0.2186, 0.8748, 0.4878],
        [0.9027, 0.0033, 0.8298, 0.3705]])
tensor([[0.7916, 0.1779, 0.6404, 0.5194],
        [0.3258, 0.7070, 0.9651, 0.2351],
        [0.4717, 0.5258, 0.1565, 0.9035]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [127]:
torch.manual_seed(42)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(42)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D) 

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [1]:
 !nvidia-smi

Sat Sep 10 08:35:02 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
import torch
torch.cuda.is_available()

True

In [4]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
torch.cuda.device_count()

1

In [7]:
tensor = torch.tensor([1,2,3])
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [8]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')